blank_issues_enabled: true
contact_links:
- name: Feature Request
  url: https://github.com/TheSuperHackers/GeneralsGameCode/discussions/categories/ideas
  about: Share your ideas or request new features to enhance the game

- name: Community Outpost Discord Server
  url: https://discord.gg/WzxQDZersE
  about: For help with miscellaneous things, join our Discord community
