name: Build Generals with VC6

on:
  push:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-generals-vc6.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-generals-vc6.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Only run for:
    # 1. Pushes to main
    # 2. Manual workflow runs
    # 3. PRs from the main repository (not forks)
    # 4. PRs that have the 'ci' label
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.full_name == github.repository || contains(github.event.pull_request.labels.*.name, 'ci')))
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache VC6 installation
        id: cache-vc6
        uses: actions/cache@v4
        with:
          path: C:\VC6
          key: vc6-permanent-cache-v1

      - name: Cache CMake Dependencies
        id: cache-cmake-deps
        uses: actions/cache@v4
        with:
          path: build\vc6\_deps
          key: cmake-deps-${{ hashFiles('cmake/**/*.cmake', '**/CMakeLists.txt') }}
          restore-keys: |
            cmake-deps-

      - name: Download VC6 Portable from Cloudflare R2
        if: steps.cache-vc6.outputs.cache-hit != 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          EXPECTED_HASH: "118D0F1ACBBD70C3F8B081CA4DBAF955FE0C6C359A76636E930AA89FDC551091"
        shell: pwsh
        run: |
          Write-Host "Downloading VC6 portable installation"
          aws s3 cp s3://github-ci/VS6_VisualStudio6.7z VS6_VisualStudio6.7z --endpoint-url $env:AWS_ENDPOINT_URL

          Write-Host "Verifying file integrity..."
          $hash = (Get-FileHash -Path VS6_VisualStudio6.7z -Algorithm SHA256).Hash
          Write-Host "Downloaded file SHA256: $hash"
          Write-Host "Expected SHA256: $env:EXPECTED_HASH"
          if ($hash -ne $env:EXPECTED_HASH) {
              Write-Error "Hash verification failed! File may be corrupted or tampered with."
              exit 1
          }

          Write-Host "Extracting archive..."
          & 7z x VS6_VisualStudio6.7z -oC:\VC6

          Write-Host "Cleaning up downloaded archive"
          Remove-Item VS6_VisualStudio6.7z

      - name: Set up VC6 environment
        shell: pwsh
        run: |
          Write-Host "Setting up environment for using Microsoft Visual C++ tools"

          # Define the base directories as local variables first
          $VSCommonDir = "C:\VC6\VC6SP6\Common"
          $MSDevDir = "C:\VC6\VC6SP6\Common\msdev98"
          $MSVCDir = "C:\VC6\VC6SP6\VC98"
          $VcOsDir = "WINNT"

          # Set the variables in GitHub environment
          "VSCommonDir=$VSCommonDir" >> $env:GITHUB_ENV
          "MSDevDir=$MSDevDir" >> $env:GITHUB_ENV
          "MSVCDir=$MSVCDir" >> $env:GITHUB_ENV
          "VcOsDir=$VcOsDir" >> $env:GITHUB_ENV

          # Set PATH
          "PATH=$MSDevDir\BIN;$MSVCDir\BIN;$VSCommonDir\TOOLS\$VcOsDir;$VSCommonDir\TOOLS;$env:PATH" >> $env:GITHUB_ENV

          # Set INCLUDE
          "INCLUDE=$MSVCDir\ATL\INCLUDE;$MSVCDir\INCLUDE;$MSVCDir\MFC\INCLUDE;$env:INCLUDE" >> $env:GITHUB_ENV

          # Set LIB
          "LIB=$MSVCDir\LIB;$MSVCDir\MFC\LIB;$env:LIB" >> $env:GITHUB_ENV

      - name: Build with CMake using VC6 preset
        shell: pwsh
        run: |
          Write-Host "Configuring project with CMake using VC6 preset - building only Generals"
          cmake --preset vc6 -DGENZH_BUILD_ZEROHOUR=OFF -DGENZH_BUILD_GENERALS=ON

          Write-Host "Building project with NMake"
          cd build\vc6
          nmake

      - name: Upload Generals executable
        uses: actions/upload-artifact@v4
        with:
          name: generals
          path: build/vc6/Generals/generals.exe
          retention-days: 3
          if-no-files-found: error
