name: Build Toolchain

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      game:
        required: true
        type: string
        description: "Game to build (Generals, GeneralsMD)"
      configurePreset:
        required: true
        type: string
        description: "CMake configure preset"
      buildPreset:
        required: true
        type: string
        description: "CMake build preset"
      tools:
        required: false
        default: true
        type: boolean
        description: "Build tools"
      extras:
        required: false
        default: false
        type: boolean
        description: "Build extras"
jobs:
  build:
    name: ${{ inputs.game }} ${{ inputs.configurePreset }} ${{ inputs.buildPreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }}
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache VC6 Installation
        if: startsWith(inputs.buildPreset, 'vc6')
        id: cache-vc6
        uses: actions/cache@v4
        with:
          path: C:\VC6
          key: vc6-permanent-cache-v1

      - name: Cache CMake Dependencies
        id: cache-cmake-deps
        uses: actions/cache@v4
        with:
          path: build\${{ inputs.buildPreset }}\_deps
          key: cmake-deps-${{ inputs.buildPreset }}-${{ hashFiles('CMakePresets.json','cmake/**/*.cmake','**/CMakeLists.txt') }}

      - name: Download VC6 Portable from Cloudflare R2
        if: ${{ startsWith(inputs.buildPreset, 'vc6') && steps.cache-vc6.outputs.cache-hit != 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          EXPECTED_HASH: "118D0F1ACBBD70C3F8B081CA4DBAF955FE0C6C359A76636E930AA89FDC551091"
        shell: pwsh
        run: |
          Write-Host "Downloading VC6 Portable Installation" -ForegroundColor Cyan
          aws s3 cp s3://github-ci/VS6_VisualStudio6.7z VS6_VisualStudio6.7z --endpoint-url $env:AWS_ENDPOINT_URL

          Write-Host "Verifying File Integrity" -ForegroundColor Cyan
          $fileHash = (Get-FileHash -Path VS6_VisualStudio6.7z -Algorithm SHA256).Hash
          Write-Host "Downloaded file SHA256: $fileHash"
          Write-Host "Expected file SHA256: $env:EXPECTED_HASH"
          if ($fileHash -ne $env:EXPECTED_HASH) {
              Write-Error "Hash verification failed! File may be corrupted or tampered with."
              exit 1
          }

          Write-Host "Extracting Archive" -ForegroundColor Cyan
          & 7z x VS6_VisualStudio6.7z -oC:\VC6
          Remove-Item VS6_VisualStudio6.7z -Verbose

      - name: Set Up VC6 Environment
        if: startsWith(inputs.buildPreset, 'vc6')
        shell: pwsh
        run: |
          $VS6_DIR = "C:\VC6\VC6SP6"
          "VS6_DIR=$VS6_DIR" >> $env:GITHUB_ENV

      - name: Set Up VC2022 Environment
        if: ${{ !startsWith(inputs.buildPreset, 'vc6') }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure ${{ inputs.game }} with CMake Using ${{ inputs.configurePreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }} Preset
        shell: pwsh
        run: |
          $buildFlags = @(
            "-DRTS_BUILD_ZEROHOUR=${{ inputs.game == 'GeneralsMD' && 'ON' || 'OFF' }}",
            "-DRTS_BUILD_GENERALS=${{ inputs.game == 'Generals' && 'ON' || 'OFF' }}"
          )

          $gamePrefix = "${{ inputs.game == 'Generals' && 'GENERALS' || 'ZEROHOUR' }}"
          $buildFlags += "-DRTS_BUILD_CORE_TOOLS=${{ inputs.tools && 'ON' || 'OFF' }}"
          $buildFlags += "-DRTS_BUILD_${gamePrefix}_TOOLS=${{ inputs.tools && 'ON' || 'OFF' }}"
          $buildFlags += "-DRTS_BUILD_CORE_EXTRAS=${{ inputs.extras && 'ON' || 'OFF' }}"
          $buildFlags += "-DRTS_BUILD_${gamePrefix}_EXTRAS=${{ inputs.extras && 'ON' || 'OFF' }}"

          Write-Host "Build flags: $($buildFlags -join ' | ')"
          cmake --preset ${{ inputs.configurePreset }} $($buildFlags -join ' ')

      - name: Build ${{ inputs.game }} with CMake Using ${{ inputs.buildPreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }} Preset
        shell: pwsh
        run: |
          cmake --build --preset ${{ inputs.buildPreset }}

      - name: Collect ${{ inputs.game }} ${{ inputs.buildPreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }} Artifact
        shell: pwsh
        run: |
          $buildDir = "build\${{ inputs.configurePreset }}"
          $artifactsDir = New-Item -ItemType Directory -Force -Path "$buildDir\${{ inputs.game }}\artifacts" -Verbose
          $configToUse = if ("${{ inputs.buildPreset }}" -match "relwithdebinfo") { "RelWithDebInfo" } elseif ("${{ inputs.buildPreset }}" -match "debug") { "Debug" } else { "Release" }
          $files = Get-ChildItem -Path "$buildDir\Core\$configToUse","$buildDir\${{ inputs.game }}\$configToUse" -File | Where-Object { $_.Extension -in @(".exe", ".dll", ".pdb") } -Verbose
          $files | Move-Item -Destination $artifactsDir -Verbose -Force

      - name: Upload ${{ inputs.game }} ${{ inputs.configurePreset }} ${{ inputs.buildPreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.game }}-${{ inputs.configurePreset }}-${{ inputs.buildPreset }}${{ inputs.tools && '+t' || '' }}${{ inputs.extras && '+e' || '' }}
          path: build\${{ inputs.configurePreset }}\${{ inputs.game }}\artifacts
          retention-days: 30
          if-no-files-found: error
