name: Build Generals with VC6

on:
  push:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-vc6-generals.yml"
      - ".github/workflows/build-vc6-common.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Generals/**"
      - "Dependencies/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/build-vc6-generals.yml"
      - ".github/workflows/build-vc6-common.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generals:
    # Only run for:
    # 1. Pushes to main
    # 2. Manual workflow runs
    # 3. PRs from the main repository (not forks)
    # 4. PRs that have the 'ci' label
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.full_name == github.repository || contains(github.event.pull_request.labels.*.name, 'ci')))
    uses: ./.github/workflows/build-vc6-common.yml
    with:
      game: "generals"
    secrets: inherit
