name: GenCI

permissions:
  contents: read
  pull-requests: write

on:
  #push:
  #  branches:
  #    - main
  #    - ci-replays
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  detect-changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      generals: ${{ steps.filter.outputs.generals }}
      generalsmd: ${{ steps.filter.outputs.generalsmd }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Filter Changed Paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ''
          filters: |
            generals:
              - 'Generals/**'
            generalsmd:
              - 'GeneralsMD/**'
            shared:
              - '.github/workflows/**'
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
              - 'cmake/**'
              - 'Core/**'
              - 'Dependencies/**'

      - name: Changes Summary
        run: |
          echo "### 🔍 File Changes Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Generals: ${{ steps.filter.outputs.generals == 'true' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- GeneralsMD: ${{ steps.filter.outputs.generalsmd == 'true' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Shared: ${{ steps.filter.outputs.shared == 'true' && '✅' || '❌' }}" >> $GITHUB_STEP_SUMMARY

  build-generals:
    name: Build Generals${{ matrix.preset && '' }}
    needs: detect-changes
    if: ${{ 'false' == 'true' }}
    #if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.generals == 'true' || needs.detect-changes.outputs.shared == 'true' }}
    strategy:
      matrix:
        include:
          # - preset: "vc6"
          #   tools: true
          #   extras: true
          # - preset: "vc6-profile"
          #   tools: true
          #   extras: true
          # - preset: "vc6-debug"
          #   tools: true
          #   extras: true
          - preset: "win32"
            tools: true
            extras: true
          - preset: "win32-profile"
            tools: true
            extras: true
          - preset: "win32-debug"
            tools: true
            extras: true
          # vcpkg builds have been disabled for now due to excessive build times of 30 minutes per preset
          # - preset: "win32-vcpkg"
          #   tools: true
          #   extras: true
          # - preset: "win32-vcpkg-profile"
          #   tools: true
          #   extras: true
          # - preset: "win32-vcpkg-debug"
          #   tools: true
          #   extras: true
      fail-fast: false
    uses: ./.github/workflows/build-toolchain.yml
    with:
      game: "Generals"
      preset: ${{ matrix.preset }}
      tools: ${{ matrix.tools }}
      extras: ${{ matrix.extras }}
    secrets: inherit

  build-generalsmd:
    name: Build GeneralsMD${{ matrix.preset && '' }}
    needs: detect-changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.generalsmd == 'true' || needs.detect-changes.outputs.shared == 'true' }}
    strategy:
      matrix:
        include:
          - preset: "vc6"
            tools: false
            extras: false
          #- preset: "vc6-profile"
          #  tools: true
          #  extras: true
          #- preset: "vc6-debug"
          #  tools: false
          #  extras: false
          - preset: "vc6-releaselog"
            tools: false
            extras: false
          #- preset: "win32"
          #  tools: true
          #  extras: true
          #- preset: "win32-profile"
          #  tools: true
          #  extras: true
          #- preset: "win32-debug"
          #  tools: true
          #  extras: true
          #- preset: "win32-debuglog"
          #  tools: true
          #  extras: true
          # vcpkg builds have been disabled for now due to excessive build times of 30 minutes per preset
          # - preset: "win32-vcpkg"
          #   tools: true
          #   extras: true
          # - preset: "win32-vcpkg-profile"
          #   tools: true
          #   extras: true
          # - preset: "win32-vcpkg-debug"
          #   tools: true
          #   extras: true
      fail-fast: false
    uses: ./.github/workflows/build-toolchain.yml
    with:
      game: "GeneralsMD"
      preset: ${{ matrix.preset }}
      tools: ${{ matrix.tools }}
      extras: ${{ matrix.extras }}
    secrets: inherit

  replaycheck-generalsmd:
    name: Replay Check (${{ matrix.preset }})
    needs: build-generalsmd
    if: ${{ github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.generalsmd == 'true' || needs.detect-changes.outputs.shared == 'true' }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - preset: "vc6"
            tools: false
            extras: false
          - preset: "vc6-releaselog"
            tools: false
            extras: false
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Game Artifact
        uses: actions/download-artifact@v4
        with:
          name: GeneralsMD-${{ matrix.preset }}
          path: build

      - name: Cache GameData files
        id: cache-gamedata
        uses: actions/cache@v4
        with:
          path: C:\GameData
          key: gamedata-permanent-cache-v1

      - name: Download GameData from Cloudflare R2
        if: ${{ steps.cache-gamedata.outputs.cache-hit != 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          EXPECTED_HASH: "3BE86F84B1E771BEA01BD2DBA39442683381AE4401716E9AE9D4AD95C8F45372"
        shell: pwsh
        run: |
          # Download trimmed gamedata of both ZH and Generals. This data cannot be used for playing because it's
          # missing textures, audio and gui files. But it's enough for replay checking.
          # It's also encrypted because it's not allowed to distribute these files.

          Write-Host "Downloading GameData" -ForegroundColor Cyan
          #aws s3 cp s3://github-ci/gen_gamedata_trimmed.7z gen_gamedata_trimmed.7z --endpoint-url $env:AWS_ENDPOINT_URL
          Invoke-WebRequest -Uri "https://gadgetpack.net/stuff/gen_gamedata_trimmed.7z" -OutFile "gen_gamedata_trimmed.7z"

          Write-Host "Verifying File Integrity" -ForegroundColor Cyan
          $fileHash = (Get-FileHash -Path gen_gamedata_trimmed.7z -Algorithm SHA256).Hash
          Write-Host "Downloaded file SHA256: $fileHash"
          Write-Host "Expected file SHA256: $env:EXPECTED_HASH"
          if ($fileHash -ne $env:EXPECTED_HASH) {
              Write-Error "Hash verification failed! File may be corrupted or tampered with."
              exit 1
          }

          Write-Host "Extracting Archive" -ForegroundColor Cyan
          & 7z x gen_gamedata_trimmed.7z -oC:\GameData
          Remove-Item gen_gamedata_trimmed.7z -Verbose

      - name: Set Up GameData
        shell: pwsh
        run: |
          $source = "C:\GameData\GeneralsMD"
          $destination = "build"
          Copy-Item -Path $source\* -Destination $destination -Recurse -Force

      - name: Set Generals InstallPath in Registry
        shell: pwsh
        run: |
          # Zero Hour loads some Generals files and needs this registry key to find the
          # Generals data files.

          $regPath = "HKCU:\SOFTWARE\Electronic Arts\EA Games\Generals"
          $installPath = "C:\GameData\Generals\"

          # Ensure the key exists
          if (-not (Test-Path $regPath)) {
            New-Item -Path $regPath -Force | Out-Null
          }

          # Set the InstallPath value
          Set-ItemProperty -Path $regPath -Name InstallPath -Value $installPath -Type String
          Write-Host "Registry key set: $regPath -> InstallPath = $installPath"

      - name: Move Replays and Maps to User Dir
        shell: pwsh
        run: |
          # These files are expected in the user dir, so we move them here.

          $source = "GeneralsMD\Test\Replays"
          $destination = "$env:USERPROFILE\Documents\Command and Conquer Generals Zero Hour Data\Replays"
          Write-Host "Move replays to $destination"
          New-Item -ItemType Directory -Path $destination -Force | Out-Null
          New-Item -ItemType Directory -Path $destination -Force | Out-Null
          Move-Item -Path "$source\*" -Destination $destination -Force

          $source = "GeneralsMD\Test\Maps"
          $destination = "$env:USERPROFILE\Documents\Command and Conquer Generals Zero Hour Data\Maps"
          Write-Host "Move maps to $destination"
          New-Item -ItemType Directory -Path $destination -Force | Out-Null
          Move-Item -Path "$source\*" -Destination $destination -Force

      - name: Run Replay Compatibility Tests
        shell: pwsh
        run: |
          $exePath = "build/generalszh.exe"
          $arguments = "-jobs 1 -headless -replay *.rep"
          $timeoutSeconds = 1500
          $stdoutPath = "stdout.log"
          $stderrPath = "stderr.log"

          if (-not (Test-Path $exePath)) {
              Write-Host "ERROR: Executable not found at $exePath"
              exit 1
          }

          # Note that the game is a gui application. That means we need to redirect console output to a file
          # in order to retrieve it.
          # Clean previous logs
          Remove-Item $stdoutPath, $stderrPath -ErrorAction SilentlyContinue

          # Start the process
          Write-Host "Run $exePath $arguments"
          $process = Start-Process -FilePath $exePath `
              -ArgumentList $arguments `
              -RedirectStandardOutput $stdoutPath `
              -RedirectStandardError $stderrPath `
              -PassThru

          # Wait with timeout
          $exited = $process.WaitForExit($timeoutSeconds * 1000)

          if (-not $exited) {
              Write-Host "ERROR: Process still running after $timeoutSeconds seconds. Killing process..."
              Stop-Process -Id $process.Id -Force
          }

          # Read output
          Write-Host "=== STDOUT ==="
          Get-Content $stdoutPath

          if ((Test-Path $stderrPath) -and (Get-Item $stderrPath).Length -gt 0) {
              Write-Host "`n=== STDERR ==="
              Get-Content $stderrPath
          }

          if (-not $exited) {
              exit 1
          }

          # Check exit code
          $exitCode = $process.ExitCode
          
          # The above doesn't work on all Windows versions. If not, try this: (see https://stackoverflow.com/a/16018287)
          #$process.HasExited | Out-Null # Needs to be called for the command below to work correctly
          #$exitCode = $process.GetType().GetField('exitCode', 'NonPublic, Instance').GetValue($process)
          #Write-Host "exit code $exitCode"

          if ($exitCode -ne 0) {
              Write-Host "ERROR: Process failed with exit code $exitCode"
              exit $exitCode
          }

          Write-Host "Success!"


      - name: List All Files in Directory (Recursive)
        if: always()
        shell: pwsh
        run: |
          $dir = "."
          Write-Host "Listing all files in $dir recursively:"
          Get-ChildItem -Path $dir -Recurse -File | ForEach-Object {
            Write-Host $_.FullName
          }

      - name: List All Files in Directory (C:\GameData)
        if: always()
        shell: pwsh
        run: |
          $dir = "C:\GameData"
          Write-Host "Listing all files in $dir recursively:"
          Get-ChildItem -Path $dir -Recurse -File | ForEach-Object {
            Write-Host $_.FullName
          }

      - name: List All Files in Directory (data)
        if: always()
        shell: pwsh
        run: |
          $dir = "$env:USERPROFILE\Documents\Command and Conquer Generals Zero Hour Data"
          Write-Host "Listing all files in $dir recursively:"
          Get-ChildItem -Path $dir -Recurse -File | ForEach-Object {
            $sizeKB = "{0:N1}" -f ($_.Length / 1KB)
            Write-Host "$($_.FullName) [$sizeKB KB]"
          }

      - name: Upload Debug Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Replay-Debug-Log-${{ matrix.preset }}
          path: build/DebugLogFile*.txt
          if-no-files-found: ignore
